# Travis CI configuration file for psycopg2

language: python

matrix:
  include:
    - arch: amd64
      python: 2.7
    - arch: amd64
      python: 3.8
    - arch: amd64
      python: 3.7
    - arch: amd64
      python: 3.6
    - arch: amd64
      python: 3.5
    - arch: amd64
      python: 3.4
    - arch: arm64
      python: 2.7
    - arch: arm64
      python: 3.8
    - arch: arm64
      python: 3.7
    - arch: arm64
      python: 3.6
    - arch: arm64
      python: 3.5
    - arch: arm64
      python: 3.4

install:
  - pip install -U pip setuptools wheel
  - pip install .
  - rm -rf psycopg2.egg-info
  - sudo scripts/travis_prepare.sh

script:
  - scripts/travis_test.sh

deploy:
  - provider: script
    script: bash scripts/travis_update_docs.sh
    on:
      branch: master

notifications:
  email: false
