# Travis CI configuration file for psycopg2

language: python

dist: bionic

arch:
  - amd64
  - arm64

python:
  - 3.5
  - 3.6
  - 3.7
  - 3.8

matrix:
  include:
    - python: 2.7
    - python: 3.4

install:
  - sudo apt-get install -y bc
  - pip install -U pip setuptools wheel
  - pip install .
  - rm -rf psycopg2.egg-info
  - sudo scripts/travis_prepare.sh

script:
  - scripts/travis_test.sh

deploy:
  - provider: script
    script: bash scripts/travis_update_docs.sh
    on:
      branch: master

notifications:
  email: false
